// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7GYLXANSQ6GxFS7jb9YbhqrYAHbNqiOs',
    appId: '1:83397494665:web:c1dae52f3b0a9c493ec358',
    messagingSenderId: '83397494665',
    projectId: 'mehyay-2d41b',
    authDomain: 'mehyay-2d41b.firebaseapp.com',
    storageBucket: 'mehyay-2d41b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEzf22SOgR2sOPtqDZpIy-C8GUJ6QyJvE',
    appId: '1:83397494665:android:0c1c44e6eccd6e263ec358',
    messagingSenderId: '83397494665',
    projectId: 'mehyay-2d41b',
    storageBucket: 'mehyay-2d41b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQXw7pKaLaXXL-5t9oOzxgnsjnz9Cq0TM',
    appId: '1:83397494665:ios:06f2d232eb09e6cd3ec358',
    messagingSenderId: '83397494665',
    projectId: 'mehyay-2d41b',
    storageBucket: 'mehyay-2d41b.appspot.com',
    iosBundleId: 'com.example.mehyay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQXw7pKaLaXXL-5t9oOzxgnsjnz9Cq0TM',
    appId: '1:83397494665:ios:509e25ad1e7d934b3ec358',
    messagingSenderId: '83397494665',
    projectId: 'mehyay-2d41b',
    storageBucket: 'mehyay-2d41b.appspot.com',
    iosBundleId: 'com.example.mehyay.RunnerTests',
  );
}
